/* Generated by scripts/gen_gl_stubs.py. Phase-1 logging stubs for libEGL. */
#define STUB_LOG_ENV "LIBEGL_STUB_LOG"
#define STUB_LOG_DEFAULT "/dev/shmem/eglstub.log"
#include <EGL/egl.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <pthread.h>
#include <dlfcn.h>
static FILE *stub_log_file;
static pthread_mutex_t stub_lock = PTHREAD_MUTEX_INITIALIZER;
static void stub_log(const char *fmt, ...) {
    va_list ap;
    pthread_mutex_lock(&stub_lock);
    if (!stub_log_file) {
        const char *p = getenv(STUB_LOG_ENV);
        stub_log_file = fopen(p ? p : STUB_LOG_DEFAULT, "a");
        if (stub_log_file) setvbuf(stub_log_file, NULL, _IOLBF, 0);
    }
    if (stub_log_file) {
        va_start(ap, fmt); vfprintf(stub_log_file, fmt, ap); va_end(ap);
        fputc('\n', stub_log_file);
    }
    pthread_mutex_unlock(&stub_lock);
}

static EGLContext stub_cur_ctx; static EGLSurface stub_cur_draw, stub_cur_read;

EGLint eglGetError(void) {
    stub_log("eglGetError ");
    return EGL_SUCCESS;
}

EGLDisplay eglGetDisplay(EGLNativeDisplayType display_id) {
    stub_log("eglGetDisplay display_id=%d", (int)display_id);
    return (EGLDisplay)1;
}

EGLBoolean eglInitialize(EGLDisplay dpy, EGLint * major, EGLint * minor) {
    stub_log("eglInitialize dpy=%d major=%p minor=%p", (int)dpy, (void*)major, (void*)minor);
    if (major) *major = 1; if (minor) *minor = 4; return EGL_TRUE;
}

EGLBoolean eglTerminate(EGLDisplay dpy) {
    stub_log("eglTerminate dpy=%d", (int)dpy);
    return EGL_TRUE;
}

const char * eglQueryString(EGLDisplay dpy, EGLint name) {
    stub_log("eglQueryString dpy=%d name=%d", (int)dpy, (int)name);
    switch (name) { case EGL_VENDOR: return "StubEGL"; case EGL_VERSION: return "1.4 stub"; case EGL_EXTENSIONS: return ""; case EGL_CLIENT_APIS: return "OpenGL_ES"; default: return ""; }
}

EGLBoolean eglGetConfigs(EGLDisplay dpy, EGLConfig * configs, EGLint config_size, EGLint * num_config) {
    stub_log("eglGetConfigs dpy=%d configs=%p config_size=%d num_config=%p", (int)dpy, (void*)configs, (int)config_size, (void*)num_config);
    if (configs && config_size > 0) configs[0] = (EGLConfig)1; if (num_config) *num_config = 1; return EGL_TRUE;
}

EGLBoolean eglChooseConfig(EGLDisplay dpy, const EGLint * attrib_list, EGLConfig * configs, EGLint config_size, EGLint * num_config) {
    stub_log("eglChooseConfig dpy=%d attrib_list=%p configs=%p config_size=%d num_config=%p", (int)dpy, (void*)attrib_list, (void*)configs, (int)config_size, (void*)num_config);
    if (attrib_list) { int i; for (i = 0; attrib_list[i] != EGL_NONE; i += 2) stub_log("  attrib 0x%x = %d", attrib_list[i], attrib_list[i+1]); } if (configs && config_size > 0) configs[0] = (EGLConfig)1; if (num_config) *num_config = 1; return EGL_TRUE;
}

EGLBoolean eglGetConfigAttrib(EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint * value) {
    stub_log("eglGetConfigAttrib dpy=%d config=%d attribute=%d value=%p", (int)dpy, (int)config, (int)attribute, (void*)value);
    switch (attribute) { case EGL_BUFFER_SIZE: *value = 32; break; case EGL_RED_SIZE: case EGL_GREEN_SIZE: case EGL_BLUE_SIZE: case EGL_ALPHA_SIZE: *value = 8; break; case EGL_DEPTH_SIZE: *value = 24; break; case EGL_STENCIL_SIZE: *value = 8; break; case EGL_CONFIG_ID: *value = 1; break; case EGL_SURFACE_TYPE: *value = EGL_WINDOW_BIT | EGL_PBUFFER_BIT; break; case EGL_RENDERABLE_TYPE: *value = EGL_OPENGL_ES2_BIT; break; case EGL_CONFORMANT: *value = EGL_OPENGL_ES2_BIT; break; case EGL_NATIVE_RENDERABLE: *value = EGL_TRUE; break; case EGL_NATIVE_VISUAL_ID: *value = 0; break; case EGL_SAMPLES: case EGL_SAMPLE_BUFFERS: *value = 0; break; case EGL_MAX_PBUFFER_WIDTH: case EGL_MAX_PBUFFER_HEIGHT: *value = 4096; break; case EGL_COLOR_BUFFER_TYPE: *value = EGL_RGB_BUFFER; break; case EGL_LEVEL: *value = 0; break; case EGL_TRANSPARENT_TYPE: *value = EGL_NONE; break; default: *value = 0; break; } return EGL_TRUE;
}

EGLSurface eglCreateWindowSurface(EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint * attrib_list) {
    stub_log("eglCreateWindowSurface dpy=%d config=%d win=%d attrib_list=%p", (int)dpy, (int)config, (int)win, (void*)attrib_list);
    static int next = 0x100; return (EGLSurface)(long)next++;
}

EGLSurface eglCreatePbufferSurface(EGLDisplay dpy, EGLConfig config, const EGLint * attrib_list) {
    stub_log("eglCreatePbufferSurface dpy=%d config=%d attrib_list=%p", (int)dpy, (int)config, (void*)attrib_list);
    static int next = 0x200; return (EGLSurface)(long)next++;
}

EGLSurface eglCreatePixmapSurface(EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint * attrib_list) {
    stub_log("eglCreatePixmapSurface dpy=%d config=%d pixmap=%d attrib_list=%p", (int)dpy, (int)config, (int)pixmap, (void*)attrib_list);
    static int next = 0x300; return (EGLSurface)(long)next++;
}

EGLBoolean eglDestroySurface(EGLDisplay dpy, EGLSurface surface) {
    stub_log("eglDestroySurface dpy=%d surface=%d", (int)dpy, (int)surface);
    return EGL_TRUE;
}

EGLBoolean eglQuerySurface(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint * value) {
    stub_log("eglQuerySurface dpy=%d surface=%d attribute=%d value=%p", (int)dpy, (int)surface, (int)attribute, (void*)value);
    switch (attribute) { case EGL_WIDTH: *value = 800; break; case EGL_HEIGHT: *value = 480; break; case EGL_CONFIG_ID: *value = 1; break; default: *value = 0; } return EGL_TRUE;
}

EGLBoolean eglBindAPI(EGLenum api) {
    stub_log("eglBindAPI api=%u", (unsigned)api);
    return EGL_TRUE;
}

EGLenum eglQueryAPI(void) {
    stub_log("eglQueryAPI ");
    return EGL_OPENGL_ES_API;
}

EGLBoolean eglWaitClient(void) {
    stub_log("eglWaitClient ");
    return EGL_TRUE;
}

EGLBoolean eglReleaseThread(void) {
    stub_log("eglReleaseThread ");
    return EGL_TRUE;
}

EGLSurface eglCreatePbufferFromClientBuffer(EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint * attrib_list) {
    stub_log("eglCreatePbufferFromClientBuffer dpy=%d buftype=%u buffer=%d config=%d attrib_list=%p", (int)dpy, (unsigned)buftype, (int)buffer, (int)config, (void*)attrib_list);
    return (EGLSurface)0;
}

EGLBoolean eglSurfaceAttrib(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value) {
    stub_log("eglSurfaceAttrib dpy=%d surface=%d attribute=%d value=%d", (int)dpy, (int)surface, (int)attribute, (int)value);
    return EGL_TRUE;
}

EGLBoolean eglBindTexImage(EGLDisplay dpy, EGLSurface surface, EGLint buffer) {
    stub_log("eglBindTexImage dpy=%d surface=%d buffer=%d", (int)dpy, (int)surface, (int)buffer);
    return EGL_TRUE;
}

EGLBoolean eglReleaseTexImage(EGLDisplay dpy, EGLSurface surface, EGLint buffer) {
    stub_log("eglReleaseTexImage dpy=%d surface=%d buffer=%d", (int)dpy, (int)surface, (int)buffer);
    return EGL_TRUE;
}

EGLBoolean eglSwapInterval(EGLDisplay dpy, EGLint interval) {
    stub_log("eglSwapInterval dpy=%d interval=%d", (int)dpy, (int)interval);
    return EGL_TRUE;
}

EGLContext eglCreateContext(EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint * attrib_list) {
    stub_log("eglCreateContext dpy=%d config=%d share_context=%d attrib_list=%p", (int)dpy, (int)config, (int)share_context, (void*)attrib_list);
    static int next = 0x400; return (EGLContext)(long)next++;
}

EGLBoolean eglDestroyContext(EGLDisplay dpy, EGLContext ctx) {
    stub_log("eglDestroyContext dpy=%d ctx=%d", (int)dpy, (int)ctx);
    return EGL_TRUE;
}

EGLBoolean eglMakeCurrent(EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx) {
    stub_log("eglMakeCurrent dpy=%d draw=%d read=%d ctx=%d", (int)dpy, (int)draw, (int)read, (int)ctx);
    stub_cur_ctx = ctx; stub_cur_draw = draw; stub_cur_read = read; return EGL_TRUE;
}

EGLContext eglGetCurrentContext(void) {
    stub_log("eglGetCurrentContext ");
    return stub_cur_ctx;
}

EGLSurface eglGetCurrentSurface(EGLint readdraw) {
    stub_log("eglGetCurrentSurface readdraw=%d", (int)readdraw);
    return readdraw == EGL_DRAW ? stub_cur_draw : stub_cur_read;
}

EGLDisplay eglGetCurrentDisplay(void) {
    stub_log("eglGetCurrentDisplay ");
    return (EGLDisplay)1;
}

EGLBoolean eglQueryContext(EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint * value) {
    stub_log("eglQueryContext dpy=%d ctx=%d attribute=%d value=%p", (int)dpy, (int)ctx, (int)attribute, (void*)value);
    switch (attribute) { case EGL_CONFIG_ID: *value = 1; break; case EGL_CONTEXT_CLIENT_TYPE: *value = EGL_OPENGL_ES_API; break; case EGL_CONTEXT_CLIENT_VERSION: *value = 2; break; case EGL_RENDER_BUFFER: *value = EGL_BACK_BUFFER; break; default: *value = 0; } return EGL_TRUE;
}

EGLBoolean eglWaitGL(void) {
    stub_log("eglWaitGL ");
    return EGL_TRUE;
}

EGLBoolean eglWaitNative(EGLint engine) {
    stub_log("eglWaitNative engine=%d", (int)engine);
    return EGL_TRUE;
}

EGLBoolean eglSwapBuffers(EGLDisplay dpy, EGLSurface surface) {
    stub_log("eglSwapBuffers dpy=%d surface=%d", (int)dpy, (int)surface);
    if (getenv("MIB_GL_HOST")) {
        void (*swap)(void) = (void (*)(void))dlsym(RTLD_DEFAULT, "mib_gl_swap");
        if (!swap) return EGL_FALSE;
        swap();
    }
    return EGL_TRUE;
}

EGLBoolean eglCopyBuffers(EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target) {
    stub_log("eglCopyBuffers dpy=%d surface=%d target=%d", (int)dpy, (int)surface, (int)target);
    return EGL_TRUE;
}

__eglMustCastToProperFunctionPointerType eglGetProcAddress(const char * procname) {
    stub_log("eglGetProcAddress procname=%p", (void*)procname);
    return (__eglMustCastToProperFunctionPointerType)0;
}
