/* Generated by scripts/gen_gl_stubs.py. Phase-1 logging stubs for libGLESv2. */
#define STUB_LOG_ENV "LIBGLESV2_STUB_LOG"
#define STUB_LOG_DEFAULT "/dev/shmem/glesstub.log"
#include <GLES2/gl2.h>
#include <GLES2/gl2ext.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <pthread.h>
static FILE *stub_log_file;
static pthread_mutex_t stub_lock = PTHREAD_MUTEX_INITIALIZER;
static void stub_log(const char *fmt, ...) {
    va_list ap;
    pthread_mutex_lock(&stub_lock);
    if (!stub_log_file) {
        const char *p = getenv(STUB_LOG_ENV);
        stub_log_file = fopen(p ? p : STUB_LOG_DEFAULT, "a");
        if (stub_log_file) setvbuf(stub_log_file, NULL, _IOLBF, 0);
    }
    if (stub_log_file) {
        va_start(ap, fmt); vfprintf(stub_log_file, fmt, ap); va_end(ap);
        fputc('\n', stub_log_file);
    }
    pthread_mutex_unlock(&stub_lock);
}

static GLuint stub_array_buffer;

void glActiveTexture(GLenum texture) {
    stub_log("glActiveTexture texture=%u", (unsigned)texture);
    
}

void glAttachShader(GLuint program, GLuint shader) {
    stub_log("glAttachShader program=%u shader=%u", (unsigned)program, (unsigned)shader);
    
}

void glBindAttribLocation(GLuint program, GLuint index, const char* name) {
    stub_log("glBindAttribLocation program=%u index=%u name=%p", (unsigned)program, (unsigned)index, (void*)name);
    
}

void glBindBuffer(GLenum target, GLuint buffer) {
    stub_log("glBindBuffer target=%u buffer=%u", (unsigned)target, (unsigned)buffer);
    if (target == 0x8892) stub_array_buffer = buffer;
}

void glBindFramebuffer(GLenum target, GLuint framebuffer) {
    stub_log("glBindFramebuffer target=%u framebuffer=%u", (unsigned)target, (unsigned)framebuffer);
    
}

void glBindRenderbuffer(GLenum target, GLuint renderbuffer) {
    stub_log("glBindRenderbuffer target=%u renderbuffer=%u", (unsigned)target, (unsigned)renderbuffer);
    
}

void glBindTexture(GLenum target, GLuint texture) {
    stub_log("glBindTexture target=%u texture=%u", (unsigned)target, (unsigned)texture);
    
}

void glBlendColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) {
    stub_log("glBlendColor red=%g green=%g blue=%g alpha=%g", (double)red, (double)green, (double)blue, (double)alpha);
    
}

void glBlendEquation(GLenum mode) {
    stub_log("glBlendEquation mode=%u", (unsigned)mode);
    
}

void glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha) {
    stub_log("glBlendEquationSeparate modeRGB=%u modeAlpha=%u", (unsigned)modeRGB, (unsigned)modeAlpha);
    
}

void glBlendFunc(GLenum sfactor, GLenum dfactor) {
    stub_log("glBlendFunc sfactor=%u dfactor=%u", (unsigned)sfactor, (unsigned)dfactor);
    
}

void glBlendFuncSeparate(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha) {
    stub_log("glBlendFuncSeparate srcRGB=%u dstRGB=%u srcAlpha=%u dstAlpha=%u", (unsigned)srcRGB, (unsigned)dstRGB, (unsigned)srcAlpha, (unsigned)dstAlpha);
    
}

void glBufferData(GLenum target, GLsizeiptr size, const void* data, GLenum usage) {
    stub_log("glBufferData target=%u size=%ld data=%p usage=%u", (unsigned)target, (long)size, (void*)data, (unsigned)usage);
    
}

void glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void* data) {
    stub_log("glBufferSubData target=%u offset=%ld size=%ld data=%p", (unsigned)target, (long)offset, (long)size, (void*)data);
    
}

GLenum glCheckFramebufferStatus(GLenum target) {
    stub_log("glCheckFramebufferStatus target=%u", (unsigned)target);
    return 0x8CD5;
}

void glClear(GLbitfield mask) {
    stub_log("glClear mask=%u", (unsigned)mask);
    
}

void glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) {
    stub_log("glClearColor red=%g green=%g blue=%g alpha=%g", (double)red, (double)green, (double)blue, (double)alpha);
    
}

void glClearDepthf(GLclampf depth) {
    stub_log("glClearDepthf depth=%g", (double)depth);
    
}

void glClearStencil(GLint s) {
    stub_log("glClearStencil s=%d", (int)s);
    
}

void glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) {
    stub_log("glColorMask red=%d green=%d blue=%d alpha=%d", (int)red, (int)green, (int)blue, (int)alpha);
    
}

void glCompileShader(GLuint shader) {
    stub_log("glCompileShader shader=%u", (unsigned)shader);
    
}

void glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data) {
    stub_log("glCompressedTexImage2D target=%u level=%d internalformat=%u width=%d height=%d border=%d imageSize=%d data=%p", (unsigned)target, (int)level, (unsigned)internalformat, (int)width, (int)height, (int)border, (int)imageSize, (void*)data);
    
}

void glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void* data) {
    stub_log("glCompressedTexSubImage2D target=%u level=%d xoffset=%d yoffset=%d width=%d height=%d format=%u imageSize=%d data=%p", (unsigned)target, (int)level, (int)xoffset, (int)yoffset, (int)width, (int)height, (unsigned)format, (int)imageSize, (void*)data);
    
}

void glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) {
    stub_log("glCopyTexImage2D target=%u level=%d internalformat=%u x=%d y=%d width=%d height=%d border=%d", (unsigned)target, (int)level, (unsigned)internalformat, (int)x, (int)y, (int)width, (int)height, (int)border);
    
}

void glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
    stub_log("glCopyTexSubImage2D target=%u level=%d xoffset=%d yoffset=%d x=%d y=%d width=%d height=%d", (unsigned)target, (int)level, (int)xoffset, (int)yoffset, (int)x, (int)y, (int)width, (int)height);
    
}

GLuint glCreateProgram(void) {
    stub_log("glCreateProgram ");
    static GLuint next = 5000; return next++;
}

GLuint glCreateShader(GLenum type) {
    stub_log("glCreateShader type=%u", (unsigned)type);
    static GLuint next = 1000; return next++;
}

void glCullFace(GLenum mode) {
    stub_log("glCullFace mode=%u", (unsigned)mode);
    
}

void glDeleteBuffers(GLsizei n, const GLuint* buffers) {
    stub_log("glDeleteBuffers n=%d buffers=%p", (int)n, (void*)buffers);
    
}

void glDeleteFramebuffers(GLsizei n, const GLuint* framebuffers) {
    stub_log("glDeleteFramebuffers n=%d framebuffers=%p", (int)n, (void*)framebuffers);
    
}

void glDeleteProgram(GLuint program) {
    stub_log("glDeleteProgram program=%u", (unsigned)program);
    
}

void glDeleteRenderbuffers(GLsizei n, const GLuint* renderbuffers) {
    stub_log("glDeleteRenderbuffers n=%d renderbuffers=%p", (int)n, (void*)renderbuffers);
    
}

void glDeleteShader(GLuint shader) {
    stub_log("glDeleteShader shader=%u", (unsigned)shader);
    
}

void glDeleteTextures(GLsizei n, const GLuint* textures) {
    stub_log("glDeleteTextures n=%d textures=%p", (int)n, (void*)textures);
    
}

void glDepthFunc(GLenum func) {
    stub_log("glDepthFunc func=%u", (unsigned)func);
    
}

void glDepthMask(GLboolean flag) {
    stub_log("glDepthMask flag=%d", (int)flag);
    
}

void glDepthRangef(GLclampf zNear, GLclampf zFar) {
    stub_log("glDepthRangef zNear=%g zFar=%g", (double)zNear, (double)zFar);
    
}

void glDetachShader(GLuint program, GLuint shader) {
    stub_log("glDetachShader program=%u shader=%u", (unsigned)program, (unsigned)shader);
    
}

void glDisable(GLenum cap) {
    stub_log("glDisable cap=%u", (unsigned)cap);
    
}

void glDisableVertexAttribArray(GLuint index) {
    stub_log("glDisableVertexAttribArray index=%u", (unsigned)index);
    
}

void glDrawArrays(GLenum mode, GLint first, GLsizei count) {
    stub_log("glDrawArrays mode=%u first=%d count=%d", (unsigned)mode, (int)first, (int)count);
    
}

void glDrawElements(GLenum mode, GLsizei count, GLenum type, const void* indices) {
    stub_log("glDrawElements mode=%u count=%d type=%u indices=%p", (unsigned)mode, (int)count, (unsigned)type, (void*)indices);
    
}

void glEnable(GLenum cap) {
    stub_log("glEnable cap=%u", (unsigned)cap);
    
}

void glEnableVertexAttribArray(GLuint index) {
    stub_log("glEnableVertexAttribArray index=%u", (unsigned)index);
    
}

void glFinish(void) {
    stub_log("glFinish ");
    
}

void glFlush(void) {
    stub_log("glFlush ");
    
}

void glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) {
    stub_log("glFramebufferRenderbuffer target=%u attachment=%u renderbuffertarget=%u renderbuffer=%u", (unsigned)target, (unsigned)attachment, (unsigned)renderbuffertarget, (unsigned)renderbuffer);
    
}

void glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) {
    stub_log("glFramebufferTexture2D target=%u attachment=%u textarget=%u texture=%u level=%d", (unsigned)target, (unsigned)attachment, (unsigned)textarget, (unsigned)texture, (int)level);
    
}

void glFrontFace(GLenum mode) {
    stub_log("glFrontFace mode=%u", (unsigned)mode);
    
}

void glGenBuffers(GLsizei n, GLuint* buffers) {
    stub_log("glGenBuffers n=%d buffers=%p", (int)n, (void*)buffers);
    static GLuint next = 1; for (GLsizei i = 0; i < n; i++) buffers[i] = next++;
}

void glGenerateMipmap(GLenum target) {
    stub_log("glGenerateMipmap target=%u", (unsigned)target);
    
}

void glGenFramebuffers(GLsizei n, GLuint* framebuffers) {
    stub_log("glGenFramebuffers n=%d framebuffers=%p", (int)n, (void*)framebuffers);
    static GLuint next = 1; for (GLsizei i = 0; i < n; i++) framebuffers[i] = next++;
}

void glGenRenderbuffers(GLsizei n, GLuint* renderbuffers) {
    stub_log("glGenRenderbuffers n=%d renderbuffers=%p", (int)n, (void*)renderbuffers);
    static GLuint next = 1; for (GLsizei i = 0; i < n; i++) renderbuffers[i] = next++;
}

void glGenTextures(GLsizei n, GLuint* textures) {
    stub_log("glGenTextures n=%d textures=%p", (int)n, (void*)textures);
    static GLuint next = 1; for (GLsizei i = 0; i < n; i++) textures[i] = next++;
}

void glGetActiveAttrib(GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, char* name) {
    stub_log("glGetActiveAttrib program=%u index=%u bufsize=%d length=%p size=%p type=%p name=%p", (unsigned)program, (unsigned)index, (int)bufsize, (void*)length, (void*)size, (void*)type, (void*)name);
    if (length) *length = 0; if (size) *size = 1; if (type) *type = 0x8B50; if (bufsize > 0) name[0] = 0;
}

void glGetActiveUniform(GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, char* name) {
    stub_log("glGetActiveUniform program=%u index=%u bufsize=%d length=%p size=%p type=%p name=%p", (unsigned)program, (unsigned)index, (int)bufsize, (void*)length, (void*)size, (void*)type, (void*)name);
    if (length) *length = 0; if (size) *size = 1; if (type) *type = 0x8B50; if (bufsize > 0) name[0] = 0;
}

void glGetAttachedShaders(GLuint program, GLsizei maxcount, GLsizei* count, GLuint* shaders) {
    stub_log("glGetAttachedShaders program=%u maxcount=%d count=%p shaders=%p", (unsigned)program, (int)maxcount, (void*)count, (void*)shaders);
    if (count) *count = 0;
}

int glGetAttribLocation(GLuint program, const char* name) {
    stub_log("glGetAttribLocation program=%u name=%p", (unsigned)program, (void*)name);
    static GLint next = 0; return next++ % 16;
}

void glGetBooleanv(GLenum pname, GLboolean* params) {
    stub_log("glGetBooleanv pname=%u params=%p", (unsigned)pname, (void*)params);
    *params = 0;
}

void glGetBufferParameteriv(GLenum target, GLenum pname, GLint* params) {
    stub_log("glGetBufferParameteriv target=%u pname=%u params=%p", (unsigned)target, (unsigned)pname, (void*)params);
    *params = 0;
}

GLenum glGetError(void) {
    stub_log("glGetError ");
    return 0;
}

void glGetFloatv(GLenum pname, GLfloat* params) {
    stub_log("glGetFloatv pname=%u params=%p", (unsigned)pname, (void*)params);
    switch (pname) { case 0x846D: params[0] = 1; params[1] = 8; break; case 0x846E: params[0] = 1; params[1] = 1; break; default: params[0] = 0; }
}

void glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint* params) {
    stub_log("glGetFramebufferAttachmentParameteriv target=%u attachment=%u pname=%u params=%p", (unsigned)target, (unsigned)attachment, (unsigned)pname, (void*)params);
    *params = 0;
}

void glGetIntegerv(GLenum pname, GLint* params) {
    stub_log("glGetIntegerv pname=%u params=%p", (unsigned)pname, (void*)params);
    switch (pname) { case 0x8DFA: *params = 1; break; /* SHADER_COMPILER */ case 0x8DF9: *params = 0; break; /* NUM_SHADER_BINARY_FORMATS */ case 0x8DFB: *params = 128; break; case 0x8DFC: *params = 15; break; case 0x8DFD: *params = 16; break; case 0x0D33: *params = 4096; break; case 0x851C: *params = 4096; break; case 0x8869: *params = 16; break; case 0x8872: *params = 16; break; case 0x8B4D: *params = 16; break; case 0x8B4C: *params = 8; break; case 0x8CDF: *params = 1; break; case 0x84E8: *params = 4096; break; case 0x0D3A: *params = 1; break; case 0x0D32: params[0] = params[1] = 4096; break; case 0x8B9A: *params = 0x1401; break; case 0x8B9B: *params = 0x1908; break; default: *params = 0; break; }
}

void glGetProgramiv(GLuint program, GLenum pname, GLint* params) {
    stub_log("glGetProgramiv program=%u pname=%u params=%p", (unsigned)program, (unsigned)pname, (void*)params);
    if (pname == 0x8B82) *params = 1; else if (pname == 0x8B84) *params = 0; else *params = 0;
}

void glGetProgramInfoLog(GLuint program, GLsizei bufsize, GLsizei* length, char* infolog) {
    stub_log("glGetProgramInfoLog program=%u bufsize=%d length=%p infolog=%p", (unsigned)program, (int)bufsize, (void*)length, (void*)infolog);
    if (length) *length = 0; if (bufsize > 0) infolog[0] = 0;
}

void glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint* params) {
    stub_log("glGetRenderbufferParameteriv target=%u pname=%u params=%p", (unsigned)target, (unsigned)pname, (void*)params);
    *params = 0;
}

void glGetShaderiv(GLuint shader, GLenum pname, GLint* params) {
    stub_log("glGetShaderiv shader=%u pname=%u params=%p", (unsigned)shader, (unsigned)pname, (void*)params);
    if (pname == 0x8B81) *params = 1; else if (pname == 0x8B84) *params = 0; else *params = 0;
}

void glGetShaderInfoLog(GLuint shader, GLsizei bufsize, GLsizei* length, char* infolog) {
    stub_log("glGetShaderInfoLog shader=%u bufsize=%d length=%p infolog=%p", (unsigned)shader, (int)bufsize, (void*)length, (void*)infolog);
    if (length) *length = 0; if (bufsize > 0) infolog[0] = 0;
}

void glGetShaderPrecisionFormat(GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision) {
    stub_log("glGetShaderPrecisionFormat shadertype=%u precisiontype=%u range=%p precision=%p", (unsigned)shadertype, (unsigned)precisiontype, (void*)range, (void*)precision);
    range[0] = range[1] = 127; *precision = 23;
}

void glGetShaderSource(GLuint shader, GLsizei bufsize, GLsizei* length, char* source) {
    stub_log("glGetShaderSource shader=%u bufsize=%d length=%p source=%p", (unsigned)shader, (int)bufsize, (void*)length, (void*)source);
    if (length) *length = 0; if (bufsize > 0) source[0] = 0;
}

const GLubyte* glGetString(GLenum name) {
    stub_log("glGetString name=%u", (unsigned)name);
    switch (name) { case 0x1F00: return (const GLubyte*)"StubVendor"; case 0x1F01: return (const GLubyte*)"StubRenderer"; case 0x1F02: return (const GLubyte*)"OpenGL ES 2.0"; case 0x8B8C: return (const GLubyte*)"OpenGL ES GLSL ES 1.00"; case 0x1F03: return (const GLubyte*)""; default: return (const GLubyte*)""; }
}

void glGetTexParameterfv(GLenum target, GLenum pname, GLfloat* params) {
    stub_log("glGetTexParameterfv target=%u pname=%u params=%p", (unsigned)target, (unsigned)pname, (void*)params);
    *params = 0;
}

void glGetTexParameteriv(GLenum target, GLenum pname, GLint* params) {
    stub_log("glGetTexParameteriv target=%u pname=%u params=%p", (unsigned)target, (unsigned)pname, (void*)params);
    *params = 0;
}

void glGetUniformfv(GLuint program, GLint location, GLfloat* params) {
    stub_log("glGetUniformfv program=%u location=%d params=%p", (unsigned)program, (int)location, (void*)params);
    *params = 0;
}

void glGetUniformiv(GLuint program, GLint location, GLint* params) {
    stub_log("glGetUniformiv program=%u location=%d params=%p", (unsigned)program, (int)location, (void*)params);
    *params = 0;
}

int glGetUniformLocation(GLuint program, const char* name) {
    stub_log("glGetUniformLocation program=%u name=%p", (unsigned)program, (void*)name);
    static GLint next = 100; return next++;
}

void glGetVertexAttribfv(GLuint index, GLenum pname, GLfloat* params) {
    stub_log("glGetVertexAttribfv index=%u pname=%u params=%p", (unsigned)index, (unsigned)pname, (void*)params);
    *params = 0;
}

void glGetVertexAttribiv(GLuint index, GLenum pname, GLint* params) {
    stub_log("glGetVertexAttribiv index=%u pname=%u params=%p", (unsigned)index, (unsigned)pname, (void*)params);
    *params = 0;
}

void glGetVertexAttribPointerv(GLuint index, GLenum pname, void** pointer) {
    stub_log("glGetVertexAttribPointerv index=%u pname=%u pointer=%p", (unsigned)index, (unsigned)pname, (void*)pointer);
    *pointer = 0;
}

void glHint(GLenum target, GLenum mode) {
    stub_log("glHint target=%u mode=%u", (unsigned)target, (unsigned)mode);
    
}

GLboolean glIsBuffer(GLuint buffer) {
    stub_log("glIsBuffer buffer=%u", (unsigned)buffer);
    return 1;
}

GLboolean glIsEnabled(GLenum cap) {
    stub_log("glIsEnabled cap=%u", (unsigned)cap);
    return 0;
}

GLboolean glIsFramebuffer(GLuint framebuffer) {
    stub_log("glIsFramebuffer framebuffer=%u", (unsigned)framebuffer);
    return 1;
}

GLboolean glIsProgram(GLuint program) {
    stub_log("glIsProgram program=%u", (unsigned)program);
    return 1;
}

GLboolean glIsRenderbuffer(GLuint renderbuffer) {
    stub_log("glIsRenderbuffer renderbuffer=%u", (unsigned)renderbuffer);
    return 1;
}

GLboolean glIsShader(GLuint shader) {
    stub_log("glIsShader shader=%u", (unsigned)shader);
    return 1;
}

GLboolean glIsTexture(GLuint texture) {
    stub_log("glIsTexture texture=%u", (unsigned)texture);
    return 1;
}

void glLineWidth(GLfloat width) {
    stub_log("glLineWidth width=%g", (double)width);
    
}

void glLinkProgram(GLuint program) {
    stub_log("glLinkProgram program=%u", (unsigned)program);
    
}

void glPixelStorei(GLenum pname, GLint param) {
    stub_log("glPixelStorei pname=%u param=%d", (unsigned)pname, (int)param);
    
}

void glPolygonOffset(GLfloat factor, GLfloat units) {
    stub_log("glPolygonOffset factor=%g units=%g", (double)factor, (double)units);
    
}

void glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels) {
    stub_log("glReadPixels x=%d y=%d width=%d height=%d format=%u type=%u pixels=%p", (int)x, (int)y, (int)width, (int)height, (unsigned)format, (unsigned)type, (void*)pixels);
    memset(pixels, 0, (size_t)width * height * 4);
}

void glReleaseShaderCompiler(void) {
    stub_log("glReleaseShaderCompiler ");
    
}

void glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) {
    stub_log("glRenderbufferStorage target=%u internalformat=%u width=%d height=%d", (unsigned)target, (unsigned)internalformat, (int)width, (int)height);
    
}

void glSampleCoverage(GLclampf value, GLboolean invert) {
    stub_log("glSampleCoverage value=%g invert=%d", (double)value, (int)invert);
    
}

void glScissor(GLint x, GLint y, GLsizei width, GLsizei height) {
    stub_log("glScissor x=%d y=%d width=%d height=%d", (int)x, (int)y, (int)width, (int)height);
    
}

void glShaderBinary(GLsizei n, const GLuint* shaders, GLenum binaryformat, const void* binary, GLsizei length) {
    stub_log("glShaderBinary n=%d shaders=%p binaryformat=%u binary=%p length=%d", (int)n, (void*)shaders, (unsigned)binaryformat, (void*)binary, (int)length);
    
}

void glShaderSource(GLuint shader, GLsizei count, const char** string, const GLint* length) {
    stub_log("glShaderSource shader=%u count=%d string=%p length=%p", (unsigned)shader, (int)count, (void*)string, (void*)length);
    for (GLsizei i = 0; i < count; i++) { int l = (length && length[i] >= 0) ? length[i] : (int)strlen(string[i]); stub_log("  shader %u source[%d] (%d bytes): %.*s", shader, i, l, l > 400 ? 400 : l, string[i]); }
}

void glStencilFunc(GLenum func, GLint ref, GLuint mask) {
    stub_log("glStencilFunc func=%u ref=%d mask=%u", (unsigned)func, (int)ref, (unsigned)mask);
    
}

void glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask) {
    stub_log("glStencilFuncSeparate face=%u func=%u ref=%d mask=%u", (unsigned)face, (unsigned)func, (int)ref, (unsigned)mask);
    
}

void glStencilMask(GLuint mask) {
    stub_log("glStencilMask mask=%u", (unsigned)mask);
    
}

void glStencilMaskSeparate(GLenum face, GLuint mask) {
    stub_log("glStencilMaskSeparate face=%u mask=%u", (unsigned)face, (unsigned)mask);
    
}

void glStencilOp(GLenum fail, GLenum zfail, GLenum zpass) {
    stub_log("glStencilOp fail=%u zfail=%u zpass=%u", (unsigned)fail, (unsigned)zfail, (unsigned)zpass);
    
}

void glStencilOpSeparate(GLenum face, GLenum fail, GLenum zfail, GLenum zpass) {
    stub_log("glStencilOpSeparate face=%u fail=%u zfail=%u zpass=%u", (unsigned)face, (unsigned)fail, (unsigned)zfail, (unsigned)zpass);
    
}

void glTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void* pixels) {
    stub_log("glTexImage2D target=%u level=%d internalformat=%u width=%d height=%d border=%d format=%u type=%u pixels=%p", (unsigned)target, (int)level, (unsigned)internalformat, (int)width, (int)height, (int)border, (unsigned)format, (unsigned)type, (void*)pixels);
    
}

void glTexParameterf(GLenum target, GLenum pname, GLfloat param) {
    stub_log("glTexParameterf target=%u pname=%u param=%g", (unsigned)target, (unsigned)pname, (double)param);
    
}

void glTexParameterfv(GLenum target, GLenum pname, const GLfloat* params) {
    stub_log("glTexParameterfv target=%u pname=%u params=%p", (unsigned)target, (unsigned)pname, (void*)params);
    
}

void glTexParameteri(GLenum target, GLenum pname, GLint param) {
    stub_log("glTexParameteri target=%u pname=%u param=%d", (unsigned)target, (unsigned)pname, (int)param);
    
}

void glTexParameteriv(GLenum target, GLenum pname, const GLint* params) {
    stub_log("glTexParameteriv target=%u pname=%u params=%p", (unsigned)target, (unsigned)pname, (void*)params);
    
}

void glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels) {
    stub_log("glTexSubImage2D target=%u level=%d xoffset=%d yoffset=%d width=%d height=%d format=%u type=%u pixels=%p", (unsigned)target, (int)level, (int)xoffset, (int)yoffset, (int)width, (int)height, (unsigned)format, (unsigned)type, (void*)pixels);
    
}

void glUniform1f(GLint location, GLfloat x) {
    stub_log("glUniform1f location=%d x=%g", (int)location, (double)x);
    
}

void glUniform1fv(GLint location, GLsizei count, const GLfloat* v) {
    stub_log("glUniform1fv location=%d count=%d v=%p", (int)location, (int)count, (void*)v);
    
}

void glUniform1i(GLint location, GLint x) {
    stub_log("glUniform1i location=%d x=%d", (int)location, (int)x);
    
}

void glUniform1iv(GLint location, GLsizei count, const GLint* v) {
    stub_log("glUniform1iv location=%d count=%d v=%p", (int)location, (int)count, (void*)v);
    
}

void glUniform2f(GLint location, GLfloat x, GLfloat y) {
    stub_log("glUniform2f location=%d x=%g y=%g", (int)location, (double)x, (double)y);
    
}

void glUniform2fv(GLint location, GLsizei count, const GLfloat* v) {
    stub_log("glUniform2fv location=%d count=%d v=%p", (int)location, (int)count, (void*)v);
    
}

void glUniform2i(GLint location, GLint x, GLint y) {
    stub_log("glUniform2i location=%d x=%d y=%d", (int)location, (int)x, (int)y);
    
}

void glUniform2iv(GLint location, GLsizei count, const GLint* v) {
    stub_log("glUniform2iv location=%d count=%d v=%p", (int)location, (int)count, (void*)v);
    
}

void glUniform3f(GLint location, GLfloat x, GLfloat y, GLfloat z) {
    stub_log("glUniform3f location=%d x=%g y=%g z=%g", (int)location, (double)x, (double)y, (double)z);
    
}

void glUniform3fv(GLint location, GLsizei count, const GLfloat* v) {
    stub_log("glUniform3fv location=%d count=%d v=%p", (int)location, (int)count, (void*)v);
    
}

void glUniform3i(GLint location, GLint x, GLint y, GLint z) {
    stub_log("glUniform3i location=%d x=%d y=%d z=%d", (int)location, (int)x, (int)y, (int)z);
    
}

void glUniform3iv(GLint location, GLsizei count, const GLint* v) {
    stub_log("glUniform3iv location=%d count=%d v=%p", (int)location, (int)count, (void*)v);
    
}

void glUniform4f(GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w) {
    stub_log("glUniform4f location=%d x=%g y=%g z=%g w=%g", (int)location, (double)x, (double)y, (double)z, (double)w);
    
}

void glUniform4fv(GLint location, GLsizei count, const GLfloat* v) {
    stub_log("glUniform4fv location=%d count=%d v=%p", (int)location, (int)count, (void*)v);
    
}

void glUniform4i(GLint location, GLint x, GLint y, GLint z, GLint w) {
    stub_log("glUniform4i location=%d x=%d y=%d z=%d w=%d", (int)location, (int)x, (int)y, (int)z, (int)w);
    
}

void glUniform4iv(GLint location, GLsizei count, const GLint* v) {
    stub_log("glUniform4iv location=%d count=%d v=%p", (int)location, (int)count, (void*)v);
    
}

void glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
    stub_log("glUniformMatrix2fv location=%d count=%d transpose=%d value=%p", (int)location, (int)count, (int)transpose, (void*)value);
    
}

void glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
    stub_log("glUniformMatrix3fv location=%d count=%d transpose=%d value=%p", (int)location, (int)count, (int)transpose, (void*)value);
    
}

void glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
    stub_log("glUniformMatrix4fv location=%d count=%d transpose=%d value=%p", (int)location, (int)count, (int)transpose, (void*)value);
    
}

void glUseProgram(GLuint program) {
    stub_log("glUseProgram program=%u", (unsigned)program);
    
}

void glValidateProgram(GLuint program) {
    stub_log("glValidateProgram program=%u", (unsigned)program);
    
}

void glVertexAttrib1f(GLuint indx, GLfloat x) {
    stub_log("glVertexAttrib1f indx=%u x=%g", (unsigned)indx, (double)x);
    
}

void glVertexAttrib1fv(GLuint indx, const GLfloat* values) {
    stub_log("glVertexAttrib1fv indx=%u values=%p", (unsigned)indx, (void*)values);
    
}

void glVertexAttrib2f(GLuint indx, GLfloat x, GLfloat y) {
    stub_log("glVertexAttrib2f indx=%u x=%g y=%g", (unsigned)indx, (double)x, (double)y);
    
}

void glVertexAttrib2fv(GLuint indx, const GLfloat* values) {
    stub_log("glVertexAttrib2fv indx=%u values=%p", (unsigned)indx, (void*)values);
    
}

void glVertexAttrib3f(GLuint indx, GLfloat x, GLfloat y, GLfloat z) {
    stub_log("glVertexAttrib3f indx=%u x=%g y=%g z=%g", (unsigned)indx, (double)x, (double)y, (double)z);
    
}

void glVertexAttrib3fv(GLuint indx, const GLfloat* values) {
    stub_log("glVertexAttrib3fv indx=%u values=%p", (unsigned)indx, (void*)values);
    
}

void glVertexAttrib4f(GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w) {
    stub_log("glVertexAttrib4f indx=%u x=%g y=%g z=%g w=%g", (unsigned)indx, (double)x, (double)y, (double)z, (double)w);
    
}

void glVertexAttrib4fv(GLuint indx, const GLfloat* values) {
    stub_log("glVertexAttrib4fv indx=%u values=%p", (unsigned)indx, (void*)values);
    
}

void glVertexAttribPointer(GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* ptr) {
    stub_log("glVertexAttribPointer indx=%u size=%d type=%u normalized=%d stride=%d ptr=%p", (unsigned)indx, (int)size, (unsigned)type, (int)normalized, (int)stride, (void*)ptr);
    stub_log("  attrib %u bound array buffer=%u", indx, stub_array_buffer);
}

void glViewport(GLint x, GLint y, GLsizei width, GLsizei height) {
    stub_log("glViewport x=%d y=%d width=%d height=%d", (int)x, (int)y, (int)width, (int)height);
    
}

void glProgramBinaryOES(GLuint program, GLenum binaryFormat, const void* binary, GLint length) {
    stub_log("glProgramBinaryOES program=%u binaryFormat=%u binary=%p length=%d", (unsigned)program, (unsigned)binaryFormat, (void*)binary, (int)length);
    
}

void glGetProgramBinaryOES(GLuint program, GLsizei bufSize, GLsizei* length, GLenum* binaryFormat, void* binary) {
    stub_log("glGetProgramBinaryOES program=%u bufSize=%d length=%p binaryFormat=%p binary=%p", (unsigned)program, (int)bufSize, (void*)length, (void*)binaryFormat, (void*)binary);
    if (length) *length = 0;
}
