/* Generated by scripts/gen_gl_stubs.py. Phase-1 logging stubs for libGLESv2. */
#define STUB_LOG_ENV "LIBGLESV2_STUB_LOG"
#define STUB_LOG_DEFAULT "/dev/shmem/glesstub.log"
#include <GLES2/gl2.h>
#include <GLES2/gl2ext.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <pthread.h>
static FILE *stub_log_file;
static pthread_mutex_t stub_lock = PTHREAD_MUTEX_INITIALIZER;
static void stub_log(const char *fmt, ...) {
    va_list ap;
    pthread_mutex_lock(&stub_lock);
    if (!stub_log_file) {
        const char *p = getenv(STUB_LOG_ENV);
        stub_log_file = fopen(p ? p : STUB_LOG_DEFAULT, "a");
        if (stub_log_file) setvbuf(stub_log_file, NULL, _IOLBF, 0);
    }
    if (stub_log_file) {
        va_start(ap, fmt); vfprintf(stub_log_file, fmt, ap); va_end(ap);
        fputc('\n', stub_log_file);
    }
    pthread_mutex_unlock(&stub_lock);
}


#include "gl_rpc.h"
static GLuint array_buffer, element_buffer;

void glActiveTexture(GLenum texture) {
    RpcArg args[] = {{(void *)(&texture), sizeof(texture), 0}};
    uint32_t result=rpc(1,1,args,0,0);
}

void glAttachShader(GLuint program, GLuint shader) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&shader), sizeof(shader), 0}};
    uint32_t result=rpc(2,2,args,0,0);
}

void glBindAttribLocation(GLuint program, GLuint index, const char* name) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&index), sizeof(index), 0},{(void *)(name), name ? strlen(name)+1 : 0, 1}};
    uint32_t result=rpc(3,3,args,0,0);
}

void glBindBuffer(GLenum target, GLuint buffer) {
    if(target==GL_ARRAY_BUFFER) array_buffer=buffer; if(target==GL_ELEMENT_ARRAY_BUFFER) element_buffer=buffer;
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&buffer), sizeof(buffer), 0}};
    uint32_t result=rpc(4,2,args,0,0);
}

void glBindFramebuffer(GLenum target, GLuint framebuffer) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&framebuffer), sizeof(framebuffer), 0}};
    uint32_t result=rpc(5,2,args,0,0);
}

void glBindRenderbuffer(GLenum target, GLuint renderbuffer) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&renderbuffer), sizeof(renderbuffer), 0}};
    uint32_t result=rpc(6,2,args,0,0);
}

void glBindTexture(GLenum target, GLuint texture) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&texture), sizeof(texture), 0}};
    uint32_t result=rpc(7,2,args,0,0);
}

void glBlendColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) {
    RpcArg args[] = {{(void *)(&red), sizeof(red), 0},{(void *)(&green), sizeof(green), 0},{(void *)(&blue), sizeof(blue), 0},{(void *)(&alpha), sizeof(alpha), 0}};
    uint32_t result=rpc(8,4,args,0,0);
}

void glBlendEquation(GLenum mode) {
    RpcArg args[] = {{(void *)(&mode), sizeof(mode), 0}};
    uint32_t result=rpc(9,1,args,0,0);
}

void glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha) {
    RpcArg args[] = {{(void *)(&modeRGB), sizeof(modeRGB), 0},{(void *)(&modeAlpha), sizeof(modeAlpha), 0}};
    uint32_t result=rpc(10,2,args,0,0);
}

void glBlendFunc(GLenum sfactor, GLenum dfactor) {
    RpcArg args[] = {{(void *)(&sfactor), sizeof(sfactor), 0},{(void *)(&dfactor), sizeof(dfactor), 0}};
    uint32_t result=rpc(11,2,args,0,0);
}

void glBlendFuncSeparate(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha) {
    RpcArg args[] = {{(void *)(&srcRGB), sizeof(srcRGB), 0},{(void *)(&dstRGB), sizeof(dstRGB), 0},{(void *)(&srcAlpha), sizeof(srcAlpha), 0},{(void *)(&dstAlpha), sizeof(dstAlpha), 0}};
    uint32_t result=rpc(12,4,args,0,0);
}

void glBufferData(GLenum target, GLsizeiptr size, const void* data, GLenum usage) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&size), sizeof(size), 0},{(void *)(data), size, 1},{(void *)(&usage), sizeof(usage), 0}};
    uint32_t result=rpc(13,4,args,0,0);
}

void glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void* data) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&offset), sizeof(offset), 0},{(void *)(&size), sizeof(size), 0},{(void *)(data), size, 1}};
    uint32_t result=rpc(14,4,args,0,0);
}

GLenum glCheckFramebufferStatus(GLenum target) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0}};
    uint32_t result=rpc(15,1,args,0,0);
    return (GLenum)(uintptr_t)result;
}

void glClear(GLbitfield mask) {
    RpcArg args[] = {{(void *)(&mask), sizeof(mask), 0}};
    uint32_t result=rpc(16,1,args,0,0);
}

void glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) {
    RpcArg args[] = {{(void *)(&red), sizeof(red), 0},{(void *)(&green), sizeof(green), 0},{(void *)(&blue), sizeof(blue), 0},{(void *)(&alpha), sizeof(alpha), 0}};
    uint32_t result=rpc(17,4,args,0,0);
}

void glClearDepthf(GLclampf depth) {
    RpcArg args[] = {{(void *)(&depth), sizeof(depth), 0}};
    uint32_t result=rpc(18,1,args,0,0);
}

void glClearStencil(GLint s) {
    RpcArg args[] = {{(void *)(&s), sizeof(s), 0}};
    uint32_t result=rpc(19,1,args,0,0);
}

void glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) {
    RpcArg args[] = {{(void *)(&red), sizeof(red), 0},{(void *)(&green), sizeof(green), 0},{(void *)(&blue), sizeof(blue), 0},{(void *)(&alpha), sizeof(alpha), 0}};
    uint32_t result=rpc(20,4,args,0,0);
}

void glCompileShader(GLuint shader) {
    RpcArg args[] = {{(void *)(&shader), sizeof(shader), 0}};
    uint32_t result=rpc(21,1,args,0,0);
}

void glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&level), sizeof(level), 0},{(void *)(&internalformat), sizeof(internalformat), 0},{(void *)(&width), sizeof(width), 0},{(void *)(&height), sizeof(height), 0},{(void *)(&border), sizeof(border), 0},{(void *)(&imageSize), sizeof(imageSize), 0},{(void *)(data), imageSize, 1}};
    uint32_t result=rpc(22,8,args,0,0);
}

void glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void* data) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&level), sizeof(level), 0},{(void *)(&xoffset), sizeof(xoffset), 0},{(void *)(&yoffset), sizeof(yoffset), 0},{(void *)(&width), sizeof(width), 0},{(void *)(&height), sizeof(height), 0},{(void *)(&format), sizeof(format), 0},{(void *)(&imageSize), sizeof(imageSize), 0},{(void *)(data), imageSize, 1}};
    uint32_t result=rpc(23,9,args,0,0);
}

void glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&level), sizeof(level), 0},{(void *)(&internalformat), sizeof(internalformat), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&width), sizeof(width), 0},{(void *)(&height), sizeof(height), 0},{(void *)(&border), sizeof(border), 0}};
    uint32_t result=rpc(24,8,args,0,0);
}

void glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&level), sizeof(level), 0},{(void *)(&xoffset), sizeof(xoffset), 0},{(void *)(&yoffset), sizeof(yoffset), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&width), sizeof(width), 0},{(void *)(&height), sizeof(height), 0}};
    uint32_t result=rpc(25,8,args,0,0);
}

GLuint glCreateProgram(void) {
    RpcArg args[] = {{0,0,0}};
    uint32_t result=rpc(26,0,args,0,0);
    return (GLuint)(uintptr_t)result;
}

GLuint glCreateShader(GLenum type) {
    RpcArg args[] = {{(void *)(&type), sizeof(type), 0}};
    uint32_t result=rpc(27,1,args,0,0);
    return (GLuint)(uintptr_t)result;
}

void glCullFace(GLenum mode) {
    RpcArg args[] = {{(void *)(&mode), sizeof(mode), 0}};
    uint32_t result=rpc(28,1,args,0,0);
}

void glDeleteBuffers(GLsizei n, const GLuint* buffers) {
    RpcArg args[] = {{(void *)(&n), sizeof(n), 0},{(void *)(buffers), n*sizeof(GLuint), 1}};
    uint32_t result=rpc(29,2,args,0,0);
}

void glDeleteFramebuffers(GLsizei n, const GLuint* framebuffers) {
    RpcArg args[] = {{(void *)(&n), sizeof(n), 0},{(void *)(framebuffers), n*sizeof(GLuint), 1}};
    uint32_t result=rpc(30,2,args,0,0);
}

void glDeleteProgram(GLuint program) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0}};
    uint32_t result=rpc(31,1,args,0,0);
}

void glDeleteRenderbuffers(GLsizei n, const GLuint* renderbuffers) {
    RpcArg args[] = {{(void *)(&n), sizeof(n), 0},{(void *)(renderbuffers), n*sizeof(GLuint), 1}};
    uint32_t result=rpc(32,2,args,0,0);
}

void glDeleteShader(GLuint shader) {
    RpcArg args[] = {{(void *)(&shader), sizeof(shader), 0}};
    uint32_t result=rpc(33,1,args,0,0);
}

void glDeleteTextures(GLsizei n, const GLuint* textures) {
    RpcArg args[] = {{(void *)(&n), sizeof(n), 0},{(void *)(textures), n*sizeof(GLuint), 1}};
    uint32_t result=rpc(34,2,args,0,0);
}

void glDepthFunc(GLenum func) {
    RpcArg args[] = {{(void *)(&func), sizeof(func), 0}};
    uint32_t result=rpc(35,1,args,0,0);
}

void glDepthMask(GLboolean flag) {
    RpcArg args[] = {{(void *)(&flag), sizeof(flag), 0}};
    uint32_t result=rpc(36,1,args,0,0);
}

void glDepthRangef(GLclampf zNear, GLclampf zFar) {
    RpcArg args[] = {{(void *)(&zNear), sizeof(zNear), 0},{(void *)(&zFar), sizeof(zFar), 0}};
    uint32_t result=rpc(37,2,args,0,0);
}

void glDetachShader(GLuint program, GLuint shader) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&shader), sizeof(shader), 0}};
    uint32_t result=rpc(38,2,args,0,0);
}

void glDisable(GLenum cap) {
    RpcArg args[] = {{(void *)(&cap), sizeof(cap), 0}};
    uint32_t result=rpc(39,1,args,0,0);
}

void glDisableVertexAttribArray(GLuint index) {
    RpcArg args[] = {{(void *)(&index), sizeof(index), 0}};
    uint32_t result=rpc(40,1,args,0,0);
}

void glDrawArrays(GLenum mode, GLint first, GLsizei count) {
    RpcArg args[] = {{(void *)(&mode), sizeof(mode), 0},{(void *)(&first), sizeof(first), 0},{(void *)(&count), sizeof(count), 0}};
    uint32_t result=rpc(41,3,args,0,0);
}

void glDrawElements(GLenum mode, GLsizei count, GLenum type, const void* indices) {
    RpcArg args[] = {{(void *)(&mode), sizeof(mode), 0},{(void *)(&count), sizeof(count), 0},{(void *)(&type), sizeof(type), 0},{(void *)(element_buffer ? (void *)&indices : (void *)indices), element_buffer ? sizeof(indices) : count*(type==GL_UNSIGNED_BYTE?1:2), element_buffer ? 0 : 1}};
    uint32_t result=rpc(42,4,args,0,0);
}

void glEnable(GLenum cap) {
    RpcArg args[] = {{(void *)(&cap), sizeof(cap), 0}};
    uint32_t result=rpc(43,1,args,0,0);
}

void glEnableVertexAttribArray(GLuint index) {
    RpcArg args[] = {{(void *)(&index), sizeof(index), 0}};
    uint32_t result=rpc(44,1,args,0,0);
}

void glFinish(void) {
    RpcArg args[] = {{0,0,0}};
    uint32_t result=rpc(45,0,args,0,0);
}

void glFlush(void) {
    RpcArg args[] = {{0,0,0}};
    uint32_t result=rpc(46,0,args,0,0);
}

void glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&attachment), sizeof(attachment), 0},{(void *)(&renderbuffertarget), sizeof(renderbuffertarget), 0},{(void *)(&renderbuffer), sizeof(renderbuffer), 0}};
    uint32_t result=rpc(47,4,args,0,0);
}

void glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&attachment), sizeof(attachment), 0},{(void *)(&textarget), sizeof(textarget), 0},{(void *)(&texture), sizeof(texture), 0},{(void *)(&level), sizeof(level), 0}};
    uint32_t result=rpc(48,5,args,0,0);
}

void glFrontFace(GLenum mode) {
    RpcArg args[] = {{(void *)(&mode), sizeof(mode), 0}};
    uint32_t result=rpc(49,1,args,0,0);
}

void glGenBuffers(GLsizei n, GLuint* buffers) {
    RpcArg args[] = {{(void *)(&n), sizeof(n), 0},{(void *)(buffers), n*sizeof(GLuint), 2}};
    uint32_t result=rpc(50,2,args,0,0);
}

void glGenerateMipmap(GLenum target) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0}};
    uint32_t result=rpc(51,1,args,0,0);
}

void glGenFramebuffers(GLsizei n, GLuint* framebuffers) {
    RpcArg args[] = {{(void *)(&n), sizeof(n), 0},{(void *)(framebuffers), n*sizeof(GLuint), 2}};
    uint32_t result=rpc(52,2,args,0,0);
}

void glGenRenderbuffers(GLsizei n, GLuint* renderbuffers) {
    RpcArg args[] = {{(void *)(&n), sizeof(n), 0},{(void *)(renderbuffers), n*sizeof(GLuint), 2}};
    uint32_t result=rpc(53,2,args,0,0);
}

void glGenTextures(GLsizei n, GLuint* textures) {
    RpcArg args[] = {{(void *)(&n), sizeof(n), 0},{(void *)(textures), n*sizeof(GLuint), 2}};
    uint32_t result=rpc(54,2,args,0,0);
}

void glGetActiveAttrib(GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, char* name) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&index), sizeof(index), 0},{(void *)(&bufsize), sizeof(bufsize), 0},{(void *)(length), sizeof(*length), 2},{(void *)(size), sizeof(*size), 2},{(void *)(type), sizeof(*type), 2},{(void *)(name), bufsize, 2}};
    uint32_t result=rpc(55,7,args,0,0);
}

void glGetActiveUniform(GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, char* name) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&index), sizeof(index), 0},{(void *)(&bufsize), sizeof(bufsize), 0},{(void *)(length), sizeof(*length), 2},{(void *)(size), sizeof(*size), 2},{(void *)(type), sizeof(*type), 2},{(void *)(name), bufsize, 2}};
    uint32_t result=rpc(56,7,args,0,0);
}

void glGetAttachedShaders(GLuint program, GLsizei maxcount, GLsizei* count, GLuint* shaders) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&maxcount), sizeof(maxcount), 0},{(void *)(count), 0, 1},{(void *)(shaders), 0, 1}};
    stub_log("Unsupported GL bridge call: glGetAttachedShaders"); rpc_error=GL_INVALID_OPERATION;
}

int glGetAttribLocation(GLuint program, const char* name) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(name), name ? strlen(name)+1 : 0, 1}};
    uint32_t result=rpc(58,2,args,0,0);
    return (int)(uintptr_t)result;
}

void glGetBooleanv(GLenum pname, GLboolean* params) {
    RpcArg args[] = {{(void *)(&pname), sizeof(pname), 0},{(void *)(params), (pname==GL_VIEWPORT || pname==GL_SCISSOR_BOX || pname==GL_COLOR_WRITEMASK ? 4 : pname==GL_MAX_VIEWPORT_DIMS || pname==GL_ALIASED_LINE_WIDTH_RANGE || pname==GL_ALIASED_POINT_SIZE_RANGE ? 2 : 1)*sizeof(*params), 2}};
    uint32_t result=rpc(59,2,args,0,0);
}

void glGetBufferParameteriv(GLenum target, GLenum pname, GLint* params) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), sizeof(*params), 2}};
    uint32_t result=rpc(60,3,args,0,0);
}

GLenum glGetError(void) {
    if(rpc_error) { GLenum e=rpc_error; rpc_error=0; return e; }
    RpcArg args[] = {{0,0,0}};
    uint32_t result=rpc(61,0,args,0,0);
    return (GLenum)(uintptr_t)result;
}

void glGetFloatv(GLenum pname, GLfloat* params) {
    RpcArg args[] = {{(void *)(&pname), sizeof(pname), 0},{(void *)(params), (pname==GL_VIEWPORT || pname==GL_SCISSOR_BOX || pname==GL_COLOR_WRITEMASK ? 4 : pname==GL_MAX_VIEWPORT_DIMS || pname==GL_ALIASED_LINE_WIDTH_RANGE || pname==GL_ALIASED_POINT_SIZE_RANGE ? 2 : 1)*sizeof(*params), 2}};
    uint32_t result=rpc(62,2,args,0,0);
}

void glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint* params) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&attachment), sizeof(attachment), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), sizeof(*params), 2}};
    uint32_t result=rpc(63,4,args,0,0);
}

void glGetIntegerv(GLenum pname, GLint* params) {
    RpcArg args[] = {{(void *)(&pname), sizeof(pname), 0},{(void *)(params), (pname==GL_VIEWPORT || pname==GL_SCISSOR_BOX || pname==GL_COLOR_WRITEMASK ? 4 : pname==GL_MAX_VIEWPORT_DIMS || pname==GL_ALIASED_LINE_WIDTH_RANGE || pname==GL_ALIASED_POINT_SIZE_RANGE ? 2 : 1)*sizeof(*params), 2}};
    uint32_t result=rpc(64,2,args,0,0);
}

void glGetProgramiv(GLuint program, GLenum pname, GLint* params) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), sizeof(*params), 2}};
    uint32_t result=rpc(65,3,args,0,0);
}

void glGetProgramInfoLog(GLuint program, GLsizei bufsize, GLsizei* length, char* infolog) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&bufsize), sizeof(bufsize), 0},{(void *)(length), sizeof(*length), 2},{(void *)(infolog), bufsize, 2}};
    uint32_t result=rpc(66,4,args,0,0);
}

void glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint* params) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), sizeof(*params), 2}};
    uint32_t result=rpc(67,3,args,0,0);
}

void glGetShaderiv(GLuint shader, GLenum pname, GLint* params) {
    RpcArg args[] = {{(void *)(&shader), sizeof(shader), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), sizeof(*params), 2}};
    uint32_t result=rpc(68,3,args,0,0);
}

void glGetShaderInfoLog(GLuint shader, GLsizei bufsize, GLsizei* length, char* infolog) {
    RpcArg args[] = {{(void *)(&shader), sizeof(shader), 0},{(void *)(&bufsize), sizeof(bufsize), 0},{(void *)(length), sizeof(*length), 2},{(void *)(infolog), bufsize, 2}};
    uint32_t result=rpc(69,4,args,0,0);
}

void glGetShaderPrecisionFormat(GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision) {
    RpcArg args[] = {{(void *)(&shadertype), sizeof(shadertype), 0},{(void *)(&precisiontype), sizeof(precisiontype), 0},{(void *)(range), 2*sizeof(GLint), 2},{(void *)(precision), sizeof(GLint), 2}};
    uint32_t result=rpc(70,4,args,0,0);
}

void glGetShaderSource(GLuint shader, GLsizei bufsize, GLsizei* length, char* source) {
    RpcArg args[] = {{(void *)(&shader), sizeof(shader), 0},{(void *)(&bufsize), sizeof(bufsize), 0},{(void *)(length), sizeof(*length), 2},{(void *)(source), bufsize, 2}};
    uint32_t result=rpc(71,4,args,0,0);
}

const GLubyte* glGetString(GLenum name) {
    RpcArg args[] = {{(void *)(&name), sizeof(name), 0}};
    static char strings[5][65536]; unsigned slot=name==GL_VENDOR?0:name==GL_RENDERER?1:name==GL_VERSION?2:name==GL_EXTENSIONS?3:4; rpc(72,1,args,strings[slot],sizeof(strings[slot])); return (const GLubyte *)strings[slot];
}

void glGetTexParameterfv(GLenum target, GLenum pname, GLfloat* params) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), 0, 1}};
    stub_log("Unsupported GL bridge call: glGetTexParameterfv"); rpc_error=GL_INVALID_OPERATION;
}

void glGetTexParameteriv(GLenum target, GLenum pname, GLint* params) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), 0, 1}};
    stub_log("Unsupported GL bridge call: glGetTexParameteriv"); rpc_error=GL_INVALID_OPERATION;
}

void glGetUniformfv(GLuint program, GLint location, GLfloat* params) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&location), sizeof(location), 0},{(void *)(params), 0, 1}};
    stub_log("Unsupported GL bridge call: glGetUniformfv"); rpc_error=GL_INVALID_OPERATION;
}

void glGetUniformiv(GLuint program, GLint location, GLint* params) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&location), sizeof(location), 0},{(void *)(params), 0, 1}};
    stub_log("Unsupported GL bridge call: glGetUniformiv"); rpc_error=GL_INVALID_OPERATION;
}

int glGetUniformLocation(GLuint program, const char* name) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(name), name ? strlen(name)+1 : 0, 1}};
    uint32_t result=rpc(77,2,args,0,0);
    return (int)(uintptr_t)result;
}

void glGetVertexAttribfv(GLuint index, GLenum pname, GLfloat* params) {
    RpcArg args[] = {{(void *)(&index), sizeof(index), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), 0, 1}};
    stub_log("Unsupported GL bridge call: glGetVertexAttribfv"); rpc_error=GL_INVALID_OPERATION;
}

void glGetVertexAttribiv(GLuint index, GLenum pname, GLint* params) {
    RpcArg args[] = {{(void *)(&index), sizeof(index), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), 0, 1}};
    stub_log("Unsupported GL bridge call: glGetVertexAttribiv"); rpc_error=GL_INVALID_OPERATION;
}

void glGetVertexAttribPointerv(GLuint index, GLenum pname, void** pointer) {
    RpcArg args[] = {{(void *)(&index), sizeof(index), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(pointer), 0, 1}};
    stub_log("Unsupported GL bridge call: glGetVertexAttribPointerv"); rpc_error=GL_INVALID_OPERATION;
}

void glHint(GLenum target, GLenum mode) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&mode), sizeof(mode), 0}};
    uint32_t result=rpc(81,2,args,0,0);
}

GLboolean glIsBuffer(GLuint buffer) {
    RpcArg args[] = {{(void *)(&buffer), sizeof(buffer), 0}};
    uint32_t result=rpc(82,1,args,0,0);
    return (GLboolean)(uintptr_t)result;
}

GLboolean glIsEnabled(GLenum cap) {
    RpcArg args[] = {{(void *)(&cap), sizeof(cap), 0}};
    uint32_t result=rpc(83,1,args,0,0);
    return (GLboolean)(uintptr_t)result;
}

GLboolean glIsFramebuffer(GLuint framebuffer) {
    RpcArg args[] = {{(void *)(&framebuffer), sizeof(framebuffer), 0}};
    uint32_t result=rpc(84,1,args,0,0);
    return (GLboolean)(uintptr_t)result;
}

GLboolean glIsProgram(GLuint program) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0}};
    uint32_t result=rpc(85,1,args,0,0);
    return (GLboolean)(uintptr_t)result;
}

GLboolean glIsRenderbuffer(GLuint renderbuffer) {
    RpcArg args[] = {{(void *)(&renderbuffer), sizeof(renderbuffer), 0}};
    uint32_t result=rpc(86,1,args,0,0);
    return (GLboolean)(uintptr_t)result;
}

GLboolean glIsShader(GLuint shader) {
    RpcArg args[] = {{(void *)(&shader), sizeof(shader), 0}};
    uint32_t result=rpc(87,1,args,0,0);
    return (GLboolean)(uintptr_t)result;
}

GLboolean glIsTexture(GLuint texture) {
    RpcArg args[] = {{(void *)(&texture), sizeof(texture), 0}};
    uint32_t result=rpc(88,1,args,0,0);
    return (GLboolean)(uintptr_t)result;
}

void glLineWidth(GLfloat width) {
    RpcArg args[] = {{(void *)(&width), sizeof(width), 0}};
    uint32_t result=rpc(89,1,args,0,0);
}

void glLinkProgram(GLuint program) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0}};
    uint32_t result=rpc(90,1,args,0,0);
}

void glPixelStorei(GLenum pname, GLint param) {
    RpcArg args[] = {{(void *)(&pname), sizeof(pname), 0},{(void *)(&param), sizeof(param), 0}};
    uint32_t result=rpc(91,2,args,0,0);
}

void glPolygonOffset(GLfloat factor, GLfloat units) {
    RpcArg args[] = {{(void *)(&factor), sizeof(factor), 0},{(void *)(&units), sizeof(units), 0}};
    uint32_t result=rpc(92,2,args,0,0);
}

void glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels) {
    RpcArg args[] = {{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&width), sizeof(width), 0},{(void *)(&height), sizeof(height), 0},{(void *)(&format), sizeof(format), 0},{(void *)(&type), sizeof(type), 0},{(void *)(pixels), pixel_bytes(width,height,format,type), 2}};
    uint32_t result=rpc(93,7,args,0,0);
}

void glReleaseShaderCompiler(void) {
    RpcArg args[] = {{0,0,0}};
    uint32_t result=rpc(94,0,args,0,0);
}

void glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&internalformat), sizeof(internalformat), 0},{(void *)(&width), sizeof(width), 0},{(void *)(&height), sizeof(height), 0}};
    uint32_t result=rpc(95,4,args,0,0);
}

void glSampleCoverage(GLclampf value, GLboolean invert) {
    RpcArg args[] = {{(void *)(&value), sizeof(value), 0},{(void *)(&invert), sizeof(invert), 0}};
    uint32_t result=rpc(96,2,args,0,0);
}

void glScissor(GLint x, GLint y, GLsizei width, GLsizei height) {
    RpcArg args[] = {{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&width), sizeof(width), 0},{(void *)(&height), sizeof(height), 0}};
    uint32_t result=rpc(97,4,args,0,0);
}

void glShaderBinary(GLsizei n, const GLuint* shaders, GLenum binaryformat, const void* binary, GLsizei length) {
    RpcArg args[] = {{(void *)(&n), sizeof(n), 0},{(void *)(shaders), 0, 1},{(void *)(&binaryformat), sizeof(binaryformat), 0},{(void *)(binary), 0, 1},{(void *)(&length), sizeof(length), 0}};
    stub_log("Unsupported GL bridge call: glShaderBinary"); rpc_error=GL_INVALID_OPERATION;
}

void glShaderSource(GLuint shader, GLsizei count, const char** string, const GLint* length) {
    unsigned joined_size=1; int i; char *joined,*cursor; for(i=0;i<count;i++) joined_size+=(length && length[i]>=0)?length[i]:strlen(string[i]); joined=malloc(joined_size); if(!joined) { rpc_error=GL_OUT_OF_MEMORY; return; } cursor=joined; for(i=0;i<count;i++) { unsigned n=(length && length[i]>=0)?length[i]:strlen(string[i]); memcpy(cursor,string[i],n); cursor+=n; } *cursor=0;
    RpcArg args[] = {{(void *)(&shader), sizeof(shader), 0},{(void *)(&count), sizeof(count), 0},{(void *)(joined), joined_size, 1},{(void *)(0), 0, 1}};
    uint32_t result=rpc(99,4,args,0,0);
    free(joined);
}

void glStencilFunc(GLenum func, GLint ref, GLuint mask) {
    RpcArg args[] = {{(void *)(&func), sizeof(func), 0},{(void *)(&ref), sizeof(ref), 0},{(void *)(&mask), sizeof(mask), 0}};
    uint32_t result=rpc(100,3,args,0,0);
}

void glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask) {
    RpcArg args[] = {{(void *)(&face), sizeof(face), 0},{(void *)(&func), sizeof(func), 0},{(void *)(&ref), sizeof(ref), 0},{(void *)(&mask), sizeof(mask), 0}};
    uint32_t result=rpc(101,4,args,0,0);
}

void glStencilMask(GLuint mask) {
    RpcArg args[] = {{(void *)(&mask), sizeof(mask), 0}};
    uint32_t result=rpc(102,1,args,0,0);
}

void glStencilMaskSeparate(GLenum face, GLuint mask) {
    RpcArg args[] = {{(void *)(&face), sizeof(face), 0},{(void *)(&mask), sizeof(mask), 0}};
    uint32_t result=rpc(103,2,args,0,0);
}

void glStencilOp(GLenum fail, GLenum zfail, GLenum zpass) {
    RpcArg args[] = {{(void *)(&fail), sizeof(fail), 0},{(void *)(&zfail), sizeof(zfail), 0},{(void *)(&zpass), sizeof(zpass), 0}};
    uint32_t result=rpc(104,3,args,0,0);
}

void glStencilOpSeparate(GLenum face, GLenum fail, GLenum zfail, GLenum zpass) {
    RpcArg args[] = {{(void *)(&face), sizeof(face), 0},{(void *)(&fail), sizeof(fail), 0},{(void *)(&zfail), sizeof(zfail), 0},{(void *)(&zpass), sizeof(zpass), 0}};
    uint32_t result=rpc(105,4,args,0,0);
}

void glTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void* pixels) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&level), sizeof(level), 0},{(void *)(&internalformat), sizeof(internalformat), 0},{(void *)(&width), sizeof(width), 0},{(void *)(&height), sizeof(height), 0},{(void *)(&border), sizeof(border), 0},{(void *)(&format), sizeof(format), 0},{(void *)(&type), sizeof(type), 0},{(void *)(pixels), pixel_bytes(width,height,format,type), 1}};
    uint32_t result=rpc(106,9,args,0,0);
}

void glTexParameterf(GLenum target, GLenum pname, GLfloat param) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(&param), sizeof(param), 0}};
    uint32_t result=rpc(107,3,args,0,0);
}

void glTexParameterfv(GLenum target, GLenum pname, const GLfloat* params) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), 0, 1}};
    stub_log("Unsupported GL bridge call: glTexParameterfv"); rpc_error=GL_INVALID_OPERATION;
}

void glTexParameteri(GLenum target, GLenum pname, GLint param) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(&param), sizeof(param), 0}};
    uint32_t result=rpc(109,3,args,0,0);
}

void glTexParameteriv(GLenum target, GLenum pname, const GLint* params) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&pname), sizeof(pname), 0},{(void *)(params), 0, 1}};
    stub_log("Unsupported GL bridge call: glTexParameteriv"); rpc_error=GL_INVALID_OPERATION;
}

void glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels) {
    RpcArg args[] = {{(void *)(&target), sizeof(target), 0},{(void *)(&level), sizeof(level), 0},{(void *)(&xoffset), sizeof(xoffset), 0},{(void *)(&yoffset), sizeof(yoffset), 0},{(void *)(&width), sizeof(width), 0},{(void *)(&height), sizeof(height), 0},{(void *)(&format), sizeof(format), 0},{(void *)(&type), sizeof(type), 0},{(void *)(pixels), pixel_bytes(width,height,format,type), 1}};
    uint32_t result=rpc(111,9,args,0,0);
}

void glUniform1f(GLint location, GLfloat x) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&x), sizeof(x), 0}};
    uint32_t result=rpc(112,2,args,0,0);
}

void glUniform1fv(GLint location, GLsizei count, const GLfloat* v) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(v), count*1*4, 1}};
    uint32_t result=rpc(113,3,args,0,0);
}

void glUniform1i(GLint location, GLint x) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&x), sizeof(x), 0}};
    uint32_t result=rpc(114,2,args,0,0);
}

void glUniform1iv(GLint location, GLsizei count, const GLint* v) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(v), count*1*4, 1}};
    uint32_t result=rpc(115,3,args,0,0);
}

void glUniform2f(GLint location, GLfloat x, GLfloat y) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0}};
    uint32_t result=rpc(116,3,args,0,0);
}

void glUniform2fv(GLint location, GLsizei count, const GLfloat* v) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(v), count*2*4, 1}};
    uint32_t result=rpc(117,3,args,0,0);
}

void glUniform2i(GLint location, GLint x, GLint y) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0}};
    uint32_t result=rpc(118,3,args,0,0);
}

void glUniform2iv(GLint location, GLsizei count, const GLint* v) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(v), count*2*4, 1}};
    uint32_t result=rpc(119,3,args,0,0);
}

void glUniform3f(GLint location, GLfloat x, GLfloat y, GLfloat z) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&z), sizeof(z), 0}};
    uint32_t result=rpc(120,4,args,0,0);
}

void glUniform3fv(GLint location, GLsizei count, const GLfloat* v) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(v), count*3*4, 1}};
    uint32_t result=rpc(121,3,args,0,0);
}

void glUniform3i(GLint location, GLint x, GLint y, GLint z) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&z), sizeof(z), 0}};
    uint32_t result=rpc(122,4,args,0,0);
}

void glUniform3iv(GLint location, GLsizei count, const GLint* v) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(v), count*3*4, 1}};
    uint32_t result=rpc(123,3,args,0,0);
}

void glUniform4f(GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&z), sizeof(z), 0},{(void *)(&w), sizeof(w), 0}};
    uint32_t result=rpc(124,5,args,0,0);
}

void glUniform4fv(GLint location, GLsizei count, const GLfloat* v) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(v), count*4*4, 1}};
    uint32_t result=rpc(125,3,args,0,0);
}

void glUniform4i(GLint location, GLint x, GLint y, GLint z, GLint w) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&z), sizeof(z), 0},{(void *)(&w), sizeof(w), 0}};
    uint32_t result=rpc(126,5,args,0,0);
}

void glUniform4iv(GLint location, GLsizei count, const GLint* v) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(v), count*4*4, 1}};
    uint32_t result=rpc(127,3,args,0,0);
}

void glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(&transpose), sizeof(transpose), 0},{(void *)(value), count*4*sizeof(GLfloat), 1}};
    uint32_t result=rpc(128,4,args,0,0);
}

void glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(&transpose), sizeof(transpose), 0},{(void *)(value), count*9*sizeof(GLfloat), 1}};
    uint32_t result=rpc(129,4,args,0,0);
}

void glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
    RpcArg args[] = {{(void *)(&location), sizeof(location), 0},{(void *)(&count), sizeof(count), 0},{(void *)(&transpose), sizeof(transpose), 0},{(void *)(value), count*16*sizeof(GLfloat), 1}};
    uint32_t result=rpc(130,4,args,0,0);
}

void glUseProgram(GLuint program) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0}};
    uint32_t result=rpc(131,1,args,0,0);
}

void glValidateProgram(GLuint program) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0}};
    uint32_t result=rpc(132,1,args,0,0);
}

void glVertexAttrib1f(GLuint indx, GLfloat x) {
    RpcArg args[] = {{(void *)(&indx), sizeof(indx), 0},{(void *)(&x), sizeof(x), 0}};
    uint32_t result=rpc(133,2,args,0,0);
}

void glVertexAttrib1fv(GLuint indx, const GLfloat* values) {
    RpcArg args[] = {{(void *)(&indx), sizeof(indx), 0},{(void *)(values), 1*sizeof(GLfloat), 1}};
    uint32_t result=rpc(134,2,args,0,0);
}

void glVertexAttrib2f(GLuint indx, GLfloat x, GLfloat y) {
    RpcArg args[] = {{(void *)(&indx), sizeof(indx), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0}};
    uint32_t result=rpc(135,3,args,0,0);
}

void glVertexAttrib2fv(GLuint indx, const GLfloat* values) {
    RpcArg args[] = {{(void *)(&indx), sizeof(indx), 0},{(void *)(values), 2*sizeof(GLfloat), 1}};
    uint32_t result=rpc(136,2,args,0,0);
}

void glVertexAttrib3f(GLuint indx, GLfloat x, GLfloat y, GLfloat z) {
    RpcArg args[] = {{(void *)(&indx), sizeof(indx), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&z), sizeof(z), 0}};
    uint32_t result=rpc(137,4,args,0,0);
}

void glVertexAttrib3fv(GLuint indx, const GLfloat* values) {
    RpcArg args[] = {{(void *)(&indx), sizeof(indx), 0},{(void *)(values), 3*sizeof(GLfloat), 1}};
    uint32_t result=rpc(138,2,args,0,0);
}

void glVertexAttrib4f(GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w) {
    RpcArg args[] = {{(void *)(&indx), sizeof(indx), 0},{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&z), sizeof(z), 0},{(void *)(&w), sizeof(w), 0}};
    uint32_t result=rpc(139,5,args,0,0);
}

void glVertexAttrib4fv(GLuint indx, const GLfloat* values) {
    RpcArg args[] = {{(void *)(&indx), sizeof(indx), 0},{(void *)(values), 4*sizeof(GLfloat), 1}};
    uint32_t result=rpc(140,2,args,0,0);
}

void glVertexAttribPointer(GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* ptr) {
    if(!array_buffer && ptr) { rpc_error=GL_INVALID_OPERATION; stub_log("Client vertex arrays unsupported"); return; }
    RpcArg args[] = {{(void *)(&indx), sizeof(indx), 0},{(void *)(&size), sizeof(size), 0},{(void *)(&type), sizeof(type), 0},{(void *)(&normalized), sizeof(normalized), 0},{(void *)(&stride), sizeof(stride), 0},{(void *)(&ptr), sizeof(ptr), 0}};
    uint32_t result=rpc(141,6,args,0,0);
}

void glViewport(GLint x, GLint y, GLsizei width, GLsizei height) {
    RpcArg args[] = {{(void *)(&x), sizeof(x), 0},{(void *)(&y), sizeof(y), 0},{(void *)(&width), sizeof(width), 0},{(void *)(&height), sizeof(height), 0}};
    uint32_t result=rpc(142,4,args,0,0);
}

void glProgramBinaryOES(GLuint program, GLenum binaryFormat, const void* binary, GLint length) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&binaryFormat), sizeof(binaryFormat), 0},{(void *)(binary), 0, 1},{(void *)(&length), sizeof(length), 0}};
    stub_log("Unsupported GL bridge call: glProgramBinaryOES"); rpc_error=GL_INVALID_OPERATION;
}

void glGetProgramBinaryOES(GLuint program, GLsizei bufSize, GLsizei* length, GLenum* binaryFormat, void* binary) {
    RpcArg args[] = {{(void *)(&program), sizeof(program), 0},{(void *)(&bufSize), sizeof(bufSize), 0},{(void *)(length), 0, 1},{(void *)(binaryFormat), 0, 1},{(void *)(binary), 0, 1}};
    stub_log("Unsupported GL bridge call: glGetProgramBinaryOES"); rpc_error=GL_INVALID_OPERATION;
}
