#!/usr/bin/env python3
"""Generate guest-side logging stubs for libscreen.so.1, libEGL.so.1 and libGLESv2.so.1.

Phase 1 (this generator): every entry point logs its name (with a few key
arguments) to /dev/shmem/<lib>stub.log and returns benign values, so the
original SEAT HMI can be observed past its wait for the graphics subsystem.
Prototypes are parsed from the QNX 6.5 GLES2/EGL headers copied to guest/shim.
"""
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
shim = root/'guest/shim'
src = shim/'src'
src.mkdir(parents=True, exist_ok=True)


def parse_protos(text, pattern):
    protos = []
    for m in re.finditer(pattern, text, re.S | re.M):
        ret, name, params = m.group(1).strip(), m.group(2), m.group(3).strip()
        params = re.sub(r'\s+', ' ', params)
        plist = []
        if params and params != 'void':
            for p in params.split(','):
                p = p.strip()
                pm = re.match(r'(.*?)\s*\**\s*(\w+)$', p)
                ptype = p[:p.rfind(pm.group(2))].strip() if pm else p
                plist.append((ptype, pm.group(2) if pm else 'arg'))
        protos.append((ret, name, plist))
    return protos


gl = parse_protos((shim/'gl2.h').read_text(),
                  r'GL_APICALL\s+(.*?)\s+GL_APIENTRY\s+(gl\w+)\s*\((.*?)\);')
egl = parse_protos((shim/'egl.h.txt').read_text().split('=====EGLPLATFORM')[0],
                   r'^EGLAPI\s+([\w\s\*]+?)\s+EGLAPIENTRY\s+(egl\w+)\s*\(([^;]*?)\);')
imports = set((root/'reports/jsr231-native-imports.txt').read_text().split())
gl_names = {n for _, n, _ in gl}
extra_gl = sorted(n for n in imports if n.startswith('gl') and n not in gl_names
                  and not n.endswith('Injected') and not n.startswith('glTexSubImage2Ddump'))

COMMON = r'''
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <pthread.h>
static FILE *stub_log_file;
static pthread_mutex_t stub_lock = PTHREAD_MUTEX_INITIALIZER;
static void stub_log(const char *fmt, ...) {
    va_list ap;
    pthread_mutex_lock(&stub_lock);
    if (!stub_log_file) {
        const char *p = getenv(STUB_LOG_ENV);
        stub_log_file = fopen(p ? p : STUB_LOG_DEFAULT, "a");
        if (stub_log_file) setvbuf(stub_log_file, NULL, _IOLBF, 0);
    }
    if (stub_log_file) {
        va_start(ap, fmt); vfprintf(stub_log_file, fmt, ap); va_end(ap);
        fputc('\n', stub_log_file);
    }
    pthread_mutex_unlock(&stub_lock);
}
'''


def arg_fmt(ptype, name):
    t = ptype.replace('const', '').strip()
    if '*' in t:
        return '%p', f'(void*){name}'
    if t in ('GLfloat', 'GLclampf', 'float', 'double'):
        return '%g', f'(double){name}'
    if t in ('GLuint', 'GLenum', 'GLbitfield', 'unsigned int', 'EGLenum'):
        return '%u', f'(unsigned){name}'
    if t in ('GLsizeiptr', 'GLintptr', 'long', 'khronos_ssize_t'):
        return '%ld', f'(long){name}'
    return '%d', f'(int){name}'


def gen(protos, lib, log_default, special, header_includes, extra_decls='', extra_funcs=()):
    out = [f'/* Generated by scripts/gen_gl_stubs.py. Phase-1 logging stubs for {lib}. */',
           f'#define STUB_LOG_ENV "{lib.upper()}_STUB_LOG"', f'#define STUB_LOG_DEFAULT "{log_default}"',
           header_includes, COMMON, extra_decls]
    for ret, name, plist in list(protos) + list(extra_funcs):
        params = ', '.join(f'{t} {n}' for t, n in plist) or 'void'
        fmts, vals = [], []
        for t, n in plist:
            f, v = arg_fmt(t, n)
            fmts.append(f'{n}={f}'); vals.append(v)
        logline = f'stub_log("{name} ' + ' '.join(fmts) + '"' + (', ' + ', '.join(vals) if vals else '') + ');'
        body = special.get(name)
        if body is None:
            if ret == 'void':
                body = ''
            elif '*' in ret:
                body = 'return 0;'
            else:
                body = 'return 0;'
        out.append(f'{ret} {name}({params}) {{\n    {logline}\n    {body}\n}}\n')
    (src/f'{lib}_stub.c').write_text('\n'.join(out))
    return len(protos) + len(extra_funcs)


GL_SPECIAL = {
    'glGetError': 'return 0;',
    'glCreateShader': 'static GLuint next = 1000; return next++;',
    'glCreateProgram': 'static GLuint next = 5000; return next++;',
    'glGetAttribLocation': 'static GLint next = 0; return next++ % 16;',
    'glGetUniformLocation': 'static GLint next = 100; return next++;',
    'glCheckFramebufferStatus': 'return 0x8CD5;',
    'glIsEnabled': 'return 0;',
    'glIsBuffer': 'return 1;', 'glIsFramebuffer': 'return 1;', 'glIsProgram': 'return 1;',
    'glIsRenderbuffer': 'return 1;', 'glIsShader': 'return 1;', 'glIsTexture': 'return 1;',
    'glGenBuffers': 'static GLuint next = 1; for (GLsizei i = 0; i < n; i++) buffers[i] = next++;',
    'glGenTextures': 'static GLuint next = 1; for (GLsizei i = 0; i < n; i++) textures[i] = next++;',
    'glGenFramebuffers': 'static GLuint next = 1; for (GLsizei i = 0; i < n; i++) framebuffers[i] = next++;',
    'glGenRenderbuffers': 'static GLuint next = 1; for (GLsizei i = 0; i < n; i++) renderbuffers[i] = next++;',
    'glGetShaderiv': 'if (pname == 0x8B81) *params = 1; else if (pname == 0x8B84) *params = 0; else *params = 0;',
    'glGetProgramiv': 'if (pname == 0x8B82) *params = 1; else if (pname == 0x8B84) *params = 0; else *params = 0;',
    'glGetShaderInfoLog': 'if (length) *length = 0; if (bufsize > 0) infolog[0] = 0;',
    'glGetProgramInfoLog': 'if (length) *length = 0; if (bufsize > 0) infolog[0] = 0;',
    'glGetString': ('switch (name) { case 0x1F00: return (const GLubyte*)"StubVendor"; case 0x1F01: return (const GLubyte*)"StubRenderer";'
                    ' case 0x1F02: return (const GLubyte*)"OpenGL ES 2.0"; case 0x8B8C: return (const GLubyte*)"OpenGL ES GLSL ES 1.00";'
                    ' case 0x1F03: return (const GLubyte*)""; default: return (const GLubyte*)""; }'),
    'glGetIntegerv': ('switch (pname) { case 0x8DFA: *params = 1; break; /* SHADER_COMPILER */'
                      ' case 0x8DF9: *params = 0; break; /* NUM_SHADER_BINARY_FORMATS */'
                      ' case 0x8DFB: *params = 128; break; case 0x8DFC: *params = 15; break; case 0x8DFD: *params = 16; break;'
                      ' case 0x0D33: *params = 4096; break; case 0x851C: *params = 4096; break; case 0x8869: *params = 16; break;'
                      ' case 0x8872: *params = 16; break; case 0x8B4D: *params = 16; break; case 0x8B4C: *params = 8; break;'
                      ' case 0x8CDF: *params = 1; break; case 0x84E8: *params = 4096; break; case 0x0D3A: *params = 1; break;'
                      ' case 0x0D32: params[0] = params[1] = 4096; break; case 0x8B9A: *params = 0x1401; break; case 0x8B9B: *params = 0x1908; break;'
                      ' default: *params = 0; break; }'),
    'glGetFloatv': 'switch (pname) { case 0x846D: params[0] = 1; params[1] = 8; break; case 0x846E: params[0] = 1; params[1] = 1; break; default: params[0] = 0; }',
    'glGetBooleanv': '*params = 0;',
    'glGetActiveAttrib': 'if (length) *length = 0; if (size) *size = 1; if (type) *type = 0x8B50; if (bufsize > 0) name[0] = 0;',
    'glGetActiveUniform': 'if (length) *length = 0; if (size) *size = 1; if (type) *type = 0x8B50; if (bufsize > 0) name[0] = 0;',
    'glGetAttachedShaders': 'if (count) *count = 0;',
    'glGetShaderSource': 'if (length) *length = 0; if (bufsize > 0) source[0] = 0;',
    'glGetShaderPrecisionFormat': 'range[0] = range[1] = 127; *precision = 23;',
    'glGetUniformfv': '*params = 0;', 'glGetUniformiv': '*params = 0;',
    'glGetVertexAttribfv': '*params = 0;', 'glGetVertexAttribiv': '*params = 0;',
    'glGetVertexAttribPointerv': '*pointer = 0;',
    'glGetBufferParameteriv': '*params = 0;', 'glGetFramebufferAttachmentParameteriv': '*params = 0;',
    'glGetRenderbufferParameteriv': '*params = 0;', 'glGetTexParameterfv': '*params = 0;', 'glGetTexParameteriv': '*params = 0;',
    'glReadPixels': 'memset(pixels, 0, (size_t)width * height * 4);',
    'glShaderSource': ('for (GLsizei i = 0; i < count; i++) { int l = (length && length[i] >= 0) ? length[i] : (int)strlen(string[i]);'
                       ' stub_log("  shader %u source[%d] (%d bytes): %.*s", shader, i, l, l > 400 ? 400 : l, string[i]); }'),
    'glBindBuffer': 'if (target == 0x8892) stub_array_buffer = buffer;',
    'glVertexAttribPointer': 'stub_log("  attrib %u bound array buffer=%u", indx, stub_array_buffer);',
}
GL_EXTRA_DECL = 'static GLuint stub_array_buffer;\n'
gl_extra_funcs = [('void', 'glProgramBinaryOES', [('GLuint', 'program'), ('GLenum', 'binaryFormat'), ('const void*', 'binary'), ('GLint', 'length')]),
                  ('void', 'glGetProgramBinaryOES', [('GLuint', 'program'), ('GLsizei', 'bufSize'), ('GLsizei*', 'length'), ('GLenum*', 'binaryFormat'), ('void*', 'binary')])]
gl_extra_funcs = [f for f in gl_extra_funcs if f[1] in extra_gl] + \
    [('void', n, [('int', 'a'), ('int', 'b'), ('int', 'c'), ('int', 'd')]) for n in extra_gl if n not in ('glProgramBinaryOES', 'glGetProgramBinaryOES')]
GL_SPECIAL['glGetProgramBinaryOES'] = 'if (length) *length = 0;'
n_gl = gen(gl, 'libGLESv2', '/dev/shmem/glesstub.log', GL_SPECIAL, '#include <GLES2/gl2.h>\n#include <GLES2/gl2ext.h>', GL_EXTRA_DECL, gl_extra_funcs)

EGL_SPECIAL = {
    'eglGetError': 'return EGL_SUCCESS;',
    'eglGetDisplay': 'return (EGLDisplay)1;',
    'eglInitialize': 'if (major) *major = 1; if (minor) *minor = 4; return EGL_TRUE;',
    'eglTerminate': 'return EGL_TRUE;',
    'eglQueryString': ('switch (name) { case EGL_VENDOR: return "StubEGL"; case EGL_VERSION: return "1.4 stub";'
                       ' case EGL_EXTENSIONS: return ""; case EGL_CLIENT_APIS: return "OpenGL_ES"; default: return ""; }'),
    'eglGetConfigs': 'if (configs && config_size > 0) configs[0] = (EGLConfig)1; if (num_config) *num_config = 1; return EGL_TRUE;',
    'eglChooseConfig': ('if (attrib_list) { int i; for (i = 0; attrib_list[i] != EGL_NONE; i += 2) stub_log("  attrib 0x%x = %d", attrib_list[i], attrib_list[i+1]); }'
                        ' if (configs && config_size > 0) configs[0] = (EGLConfig)1; if (num_config) *num_config = 1; return EGL_TRUE;'),
    'eglGetConfigAttrib': ('switch (attribute) { case EGL_BUFFER_SIZE: *value = 32; break; case EGL_RED_SIZE: case EGL_GREEN_SIZE: case EGL_BLUE_SIZE: case EGL_ALPHA_SIZE: *value = 8; break;'
                           ' case EGL_DEPTH_SIZE: *value = 24; break; case EGL_STENCIL_SIZE: *value = 8; break; case EGL_CONFIG_ID: *value = 1; break;'
                           ' case EGL_SURFACE_TYPE: *value = EGL_WINDOW_BIT | EGL_PBUFFER_BIT; break; case EGL_RENDERABLE_TYPE: *value = EGL_OPENGL_ES2_BIT; break;'
                           ' case EGL_CONFORMANT: *value = EGL_OPENGL_ES2_BIT; break; case EGL_NATIVE_RENDERABLE: *value = EGL_TRUE; break; case EGL_NATIVE_VISUAL_ID: *value = 0; break;'
                           ' case EGL_SAMPLES: case EGL_SAMPLE_BUFFERS: *value = 0; break; case EGL_MAX_PBUFFER_WIDTH: case EGL_MAX_PBUFFER_HEIGHT: *value = 4096; break;'
                           ' case EGL_COLOR_BUFFER_TYPE: *value = EGL_RGB_BUFFER; break; case EGL_LEVEL: *value = 0; break; case EGL_TRANSPARENT_TYPE: *value = EGL_NONE; break;'
                           ' default: *value = 0; break; } return EGL_TRUE;'),
    'eglCreateWindowSurface': 'static int next = 0x100; return (EGLSurface)(long)next++;',
    'eglCreatePbufferSurface': 'static int next = 0x200; return (EGLSurface)(long)next++;',
    'eglCreatePixmapSurface': 'static int next = 0x300; return (EGLSurface)(long)next++;',
    'eglDestroySurface': 'return EGL_TRUE;',
    'eglQuerySurface': 'switch (attribute) { case EGL_WIDTH: *value = 800; break; case EGL_HEIGHT: *value = 480; break; case EGL_CONFIG_ID: *value = 1; break; default: *value = 0; } return EGL_TRUE;',
    'eglBindAPI': 'return EGL_TRUE;', 'eglQueryAPI': 'return EGL_OPENGL_ES_API;',
    'eglWaitClient': 'return EGL_TRUE;', 'eglReleaseThread': 'return EGL_TRUE;',
    'eglCreatePbufferFromClientBuffer': 'return (EGLSurface)0;',
    'eglSurfaceAttrib': 'return EGL_TRUE;', 'eglBindTexImage': 'return EGL_TRUE;', 'eglReleaseTexImage': 'return EGL_TRUE;',
    'eglSwapInterval': 'return EGL_TRUE;',
    'eglCreateContext': 'static int next = 0x400; return (EGLContext)(long)next++;',
    'eglDestroyContext': 'return EGL_TRUE;',
    'eglMakeCurrent': 'stub_cur_ctx = ctx; stub_cur_draw = draw; stub_cur_read = read; return EGL_TRUE;',
    'eglGetCurrentContext': 'return stub_cur_ctx;',
    'eglGetCurrentSurface': 'return readdraw == EGL_DRAW ? stub_cur_draw : stub_cur_read;',
    'eglGetCurrentDisplay': 'return (EGLDisplay)1;',
    'eglQueryContext': 'switch (attribute) { case EGL_CONFIG_ID: *value = 1; break; case EGL_CONTEXT_CLIENT_TYPE: *value = EGL_OPENGL_ES_API; break; case EGL_CONTEXT_CLIENT_VERSION: *value = 2; break; case EGL_RENDER_BUFFER: *value = EGL_BACK_BUFFER; break; default: *value = 0; } return EGL_TRUE;',
    'eglWaitGL': 'return EGL_TRUE;', 'eglWaitNative': 'return EGL_TRUE;',
    'eglSwapBuffers': 'return EGL_TRUE;', 'eglCopyBuffers': 'return EGL_TRUE;',
    'eglGetProcAddress': 'return (__eglMustCastToProperFunctionPointerType)0;',
}
EGL_DECL = 'static EGLContext stub_cur_ctx; static EGLSurface stub_cur_draw, stub_cur_read;\n'
n_egl = gen(egl, 'libEGL', '/dev/shmem/eglstub.log', EGL_SPECIAL, '#include <EGL/egl.h>', EGL_DECL)
print(f'generated {n_gl} GL and {n_egl} EGL stubs; extra GL: {extra_gl}')
